### PR TITLE
Add CI Forge Test Coverage

### PR DESCRIPTION
**Pull request by naszam**
- Add CI Forge Test Coverage

### CODE REVIEW

**Review by hexonaut — APPROVED** [review]
LGTM

**Comment by gbalabasquer** [comment]
> * Explicitly call `git submodule update --init --recursive`

Why? I think the other way is just better.

**Review by talbaneth — APPROVED** [review]
Not 100% sure it gives a lot of value to have the coverage running in CI without a pass/fail criteria.
I guess it still gives some value to see an overall coverage status without having to run it yourself and see where coverage is missing.

**Comment by naszam** [comment]
> Not 100% sure it gives a lot of value to have the coverage running in CI without a pass/fail criteria. I guess it still gives some value to see an overall coverage status without having to run it yourself and see where coverage is missing.

yeah, this is meant as a first iteration, waiting to see if it will be supported natively or considering a github action conditional to trigger a failure if a certain threshold of coverage is not satisfied, but open for suggestions!

**Comment by naszam** [comment]
I've just leveraged on the https://github.com/zgosalvez/github-actions-report-lcov, following @mds1 suggestion, that could be turned into an ad-hoc bash script eventually if there is interest in going to that direction and not rely on external dependencies.
cc: @gbalabasquer @talbaneth @hexonaut

**Comment by gbalabasquer** [comment]
I'm not really sure why are we even playing with this coverage thing here. If we are still in development phase of this, please use another repo or just create one for it. But for sure we shouldn't be merging this if it's gonna report failures.

**Comment by naszam** [comment]
> I'm not really sure why are we even playing with this coverage thing here. Who actually requested it? If we are still in development phase of this coverage thing, please use another repo or just create one for it. But for sure we shouldn't be merging this if it's gonna report failures.

The pr was opened here as `forge coverage` works here whilst in other more complex repos have some issues.
The minimum coverage threshold could be adjusted eventually to allow it to pass and bumped once more tests are added.
Still working on the filtering piece to allow more granular coverage and to set and higher minimum threshold.

**Comment by gbalabasquer** [comment]
I'll give my final response, I don't think we should be merging this here. It's not the place. Let's first decide if we want this to be running on CIs, if the failure (under certain percentage) is a good metric, etc. Otherwise just seems a random thing pop ping up to this repo.

**Comment by gbalabasquer** [comment]
As discussed, forge coverage CI will be treated as a separate project in a different repo until there is a team decision and final version to include in relevant projects.

**Pull request closed without merging**
